---
- name: Converge
  hosts: all
  become: true

  vars:
    dotfiles_recursive: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install git
      package:
        name: git
        state: present

    - name: Create testing directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /root/.config
        - /root/.kube

  roles:
    - role: radek_sprta.dotfiles
