---
- name: Verify
  hosts: all

  vars_files:
    - vars.yml

  tasks:
    - name: Check dotfiles state
      ansible.builtin.stat:
        path: "/root/.{{ item }}"
      register: dotfiles_symlinks
      with_items: "{{ dotfiles }}"

    - name: Assert that symlinks exist
      ansible.builtin.assert:
        that:
          - "item.stat.exists"
          - "item.stat.islnk"
      loop_control:
        label: "{{ item.item }}"
      with_items: "{{ dotfiles_symlinks.results }}"
